version: 0.2
  phases:
    install:
      - echo
      - export AWS_REGION=us-west-1
      - export SECURITY_GROUP_ID=sg-075decb0f531d1ee9
      #- export HOSTED_ZONE="rote53domainhostedzoneid"
      - export RDS_DATABASE_NAME="ntier"
      - export RDS_USER_NAME="admin"
      - export RDS_PASSWORD="password"

      #- SECURITY_GROUP_ID=$(aws ec2 create-security-group --description ${SECURITY_GROUP_NAME} --group-name ${SECURITY_GROUP_NAME} --region ${AWS_REGION} --output text)
      
      - aws ec2 authorize-security-group-ingress --group-id ${SECURITY_GROUP_ID} --protocol tcp --port 5432 --cidr 0.0.0.0/0 --region ${AWS_REGION}
      
      - aws rds create-db-instance --db-instance-identifier ${RDS_DATABASE_NAME} --db-name ${RDS_DATABASE_NAME} --vpc-security-group-ids ${SECURITY_GROUP_ID} --allocated-storage 20 --db-instance-class db.t2.small --engine mysql --master-username ${DS_USER_NAME} --master-user-password ${RDS_PASSWORD} --region ${AWS_REGION}
      
      - aws rds wait db-instance-available --db-instance-identifier ${RDS_DATABASE_NAME}

