version: 0.2
phases:
  install:
    commands:
    - export AWS_REGION="us-west-1"
    - export SECURITY_GROUP_ID="sg-075decb0f531d1ee9"
    - export RDS_DATABASE_NAME="ntier"
    - export RDS_USER_NAME="admin"
    - export RDS_PASSWORD="password"

    - aws rds create-db-instance --db-instance-identifier ${RDS_DATABASE_NAME} --db-name ${RDS_DATABASE_NAME} --vpc-security-group-ids ${SECURITY_GROUP_ID} --allocated-storage 20 --db-instance-class db.t2.small --engine mysql --master-username ${DS_USER_NAME} --master-user-password ${RDS_PASSWORD} --region ${AWS_REGION}

    - aws rds wait db-instance-available --db-instance-identifier ${RDS_DATABASE_NAME}

